FROM alpine

LABEL maintainer="MMQ <mail@mmq.dev>"
LABEL version="1.0.0"
LABEL description="This is the server image used by QuickCertS."

WORKDIR /app

# For testing
# COPY ./certs /app/certs
COPY ./configs /app/configs
COPY ./local /app/local
COPY ./logs /app/logs
COPY ./certification_server /app

RUN chmod +x /app/certification_server

EXPOSE 33333

CMD ["./certification_server"]